export const nebulae = [
	{ name: "The Veloris Nebula", id: "NGC-94283" },
	{ name: "The Aurenthi Nebula", id: "ESO-31820" },
	{ name: "The Cryovex Nebula", id: "IC-74920" },
	{ name: "The Thessalon Nebula", id: "PGC-10293" },
	{ name: "The Marduk Nebula", id: "UGC-88471" },
	{ name: "The Solivax Nebula", id: "NGC-55312" },
	{ name: "The Eryndal Nebula", id: "ESO-62741" },
	{ name: "The Kaelthos Nebula", id: "IC-39284" },
	{ name: "The Pyroven Nebula", id: "PGC-77410" },
	{ name: "The Zephyrix Nebula", id: "UGC-14823" },
	{ name: "The Noctavian Nebula", id: "NGC-82047" },
	{ name: "The Dravonis Nebula", id: "ESO-50931" },
	{ name: "The Umbralyx Nebula", id: "IC-26758" },
	{ name: "The Seraphon Nebula", id: "PGC-33894" },
	{ name: "The Volantris Nebula", id: "UGC-61207" },
	{ name: "The Calixor Nebula", id: "NGC-47832" },
	{ name: "The Thalvex Nebula", id: "ESO-91045" },
	{ name: "The Oreyndis Nebula", id: "IC-58301" },
	{ name: "The Frostwyn Nebula", id: "PGC-22916" },
	{ name: "The Ignareth Nebula", id: "UGC-70583" },
];
